# Run this script to stage and commit all training-planner feature files.
# Execute from the repo root: .\commit.ps1

$files = @(
    "backend/pom.xml",
    "backend/Dockerfile",
    "backend/.dockerignore",
    "backend/src/main/java/com/trainingplanner/TrainingPlannerApplication.java",
    "backend/src/main/java/com/trainingplanner/health/HealthController.java",
    "backend/src/main/java/com/trainingplanner/config/SecurityConfig.java",
    "backend/src/main/java/com/trainingplanner/config/GlobalExceptionHandler.java",
    "backend/src/main/resources/application.properties",
    "backend/src/test/java/com/trainingplanner/health/HealthControllerTest.java",
    "backend/src/test/resources/application-test.properties",
    "backend/src/main/java/com/trainingplanner/domain/OneRmFormula.java",
    "backend/src/main/java/com/trainingplanner/domain/OneRmCalculator.java",
    "backend/src/test/java/com/trainingplanner/domain/OneRmCalculatorTest.java",
    "backend/src/main/java/com/trainingplanner/auth/User.java",
    "backend/src/main/java/com/trainingplanner/auth/UserRepository.java",
    "backend/src/main/java/com/trainingplanner/auth/JwtService.java",
    "backend/src/main/java/com/trainingplanner/auth/JwtAuthenticationFilter.java",
    "backend/src/main/java/com/trainingplanner/auth/UserService.java",
    "backend/src/main/java/com/trainingplanner/auth/AuthController.java",
    "backend/src/main/java/com/trainingplanner/auth/dto/RegisterRequest.java",
    "backend/src/main/java/com/trainingplanner/auth/dto/LoginRequest.java",
    "backend/src/main/java/com/trainingplanner/auth/dto/RefreshRequest.java",
    "backend/src/main/java/com/trainingplanner/auth/dto/TokenResponse.java",
    "backend/src/main/java/com/trainingplanner/auth/dto/UpdateProfileRequest.java",
    "backend/src/main/java/com/trainingplanner/auth/dto/UserResponse.java",
    "backend/src/test/java/com/trainingplanner/auth/AuthIntegrationTest.java",
    "backend/src/main/java/com/trainingplanner/exercise/MovementPattern.java",
    "backend/src/main/java/com/trainingplanner/exercise/Exercise.java",
    "backend/src/main/java/com/trainingplanner/exercise/ExerciseRepository.java",
    "backend/src/main/java/com/trainingplanner/exercise/ExerciseSeedRunner.java",
    "backend/src/main/java/com/trainingplanner/exercise/ExerciseService.java",
    "backend/src/main/java/com/trainingplanner/exercise/ExerciseController.java",
    "backend/src/main/java/com/trainingplanner/exercise/dto/ExerciseResponse.java",
    "backend/src/main/java/com/trainingplanner/exercise/dto/CreateExerciseRequest.java",
    "backend/src/test/java/com/trainingplanner/exercise/ExerciseIntegrationTest.java",
    "backend/src/main/java/com/trainingplanner/block/SetType.java",
    "backend/src/main/java/com/trainingplanner/block/Block.java",
    "backend/src/main/java/com/trainingplanner/block/BlockRepository.java",
    "backend/src/main/java/com/trainingplanner/block/BlockService.java",
    "backend/src/main/java/com/trainingplanner/block/BlockController.java",
    "backend/src/main/java/com/trainingplanner/block/dto/BlockSummary.java",
    "backend/src/main/java/com/trainingplanner/block/dto/CreateBlockRequest.java",
    "backend/src/main/java/com/trainingplanner/block/dto/DuplicateBlockRequest.java",
    "backend/src/test/java/com/trainingplanner/block/BlockIntegrationTest.java",
    "backend/src/main/java/com/trainingplanner/log/WorkoutLog.java",
    "backend/src/main/java/com/trainingplanner/log/WorkoutLogRepository.java",
    "backend/src/main/java/com/trainingplanner/log/WorkoutLogService.java",
    "backend/src/main/java/com/trainingplanner/log/WorkoutLogController.java",
    "backend/src/main/java/com/trainingplanner/log/dto/CreateLogRequest.java",
    "backend/src/test/java/com/trainingplanner/log/WorkoutLogIntegrationTest.java",
    "backend/src/main/java/com/trainingplanner/progress/WeeklyOneRmTotal.java",
    "backend/src/main/java/com/trainingplanner/progress/WeeklyVolume.java",
    "backend/src/main/java/com/trainingplanner/progress/ProgressService.java",
    "backend/src/main/java/com/trainingplanner/progress/ProgressController.java",
    "backend/src/test/java/com/trainingplanner/progress/ProgressServiceTest.java",
    "backend/src/main/java/com/trainingplanner/export/CsvExportService.java",
    "backend/src/main/java/com/trainingplanner/export/CsvExportController.java",
    "backend/src/test/java/com/trainingplanner/export/CsvExportIntegrationTest.java",
    "frontend/package.json",
    "frontend/vite.config.ts",
    "frontend/tsconfig.json",
    "frontend/tsconfig.app.json",
    "frontend/tsconfig.node.json",
    "frontend/index.html",
    "frontend/src/locales/es.json",
    "frontend/src/i18n.ts",
    "frontend/src/styles/tokens.css",
    "frontend/src/styles/global.css",
    "frontend/src/main.tsx",
    "frontend/src/App.tsx",
    "frontend/src/auth/AuthContext.tsx",
    "frontend/src/api/client.ts",
    "frontend/src/api/blocks.ts",
    "frontend/src/api/logs.ts",
    "frontend/src/components/BottomNav.tsx",
    "frontend/src/components/BottomNav.module.css",
    "frontend/src/components/TopBar.tsx",
    "frontend/src/components/TopBar.module.css",
    "frontend/src/components/OfflineBanner.tsx",
    "frontend/src/components/ProtectedRoute.tsx",
    "frontend/src/components/ExercisePicker.tsx",
    "frontend/src/components/CsvExportButton.tsx",
    "frontend/src/layouts/AppLayout.tsx",
    "frontend/src/layouts/AppLayout.module.css",
    "frontend/src/pages/LoginPage.tsx",
    "frontend/src/pages/RegisterPage.tsx",
    "frontend/src/pages/AuthPage.module.css",
    "frontend/src/pages/SettingsPage.tsx",
    "frontend/src/pages/ProgressPage.tsx",
    "frontend/src/pages/blocks/BlocksListPage.tsx",
    "frontend/src/pages/blocks/BlocksListPage.module.css",
    "frontend/src/pages/blocks/BlockDetailPage.tsx",
    "frontend/src/pages/blocks/BlockEditorPage.tsx",
    "frontend/src/pages/session/SessionPage.tsx",
    "frontend/src/pages/session/SessionPage.module.css",
    "frontend/src/test/setup.ts",
    "frontend/src/test/App.test.tsx",
    "frontend/src/test/auth/AuthContext.test.tsx",
    "frontend/src/test/blocks/BlocksListPage.test.tsx",
    "frontend/src/test/components/BottomNav.test.tsx",
    "frontend/src/test/components/ProtectedRoute.test.tsx",
    "frontend/src/test/logs/offlineQueue.test.ts",
    "frontend/public/pwa-192x192.svg",
    "frontend/public/pwa-512x512.svg",
    "frontend/Dockerfile",
    "frontend/.dockerignore",
    "frontend/nginx.conf",
    "docker-compose.yml",
    "README.md",
    "setup.ps1",
    ".gitignore",
    ".claude/features/training-planner.yaml",
    ".claude/memory/changes.md"
)

foreach ($f in $files) {
    if (Test-Path $f) {
        git add $f
        Write-Host "Staged: $f"
    }
}

git commit -m "feat(training-planner): implement full MVP — scaffold, auth, exercises, blocks, gym session, 1RM, progress charts, CSV export"
Write-Host "Commit complete."
git rev-parse HEAD
